npm install; 
npm install express; 
npm install pug; 
npm install express-session; 
npm install connect-sqlite3; 
npm install sqlite3 sqlite; 
node install.js; 
node db.js; 
node db_debug.js; 
npm start; 